# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.20.0
    hooks:
      - id: stylua # or stylua-system / stylua-github
  - repo: https://github.com/kdheepak/panvimdoc
    rev: v4.0.1
    hooks:
      - id: panvimdoc-docker
        files: ^.*\.md$
        args:
          - "--project-name"
          - keymap-stats.nvim
          - "--input-file"
          - README.md
  - repo: https://github.com/lunarmodules/luacheck
    rev: v1.1.2
    hooks:
      - id: luacheck
        name: Luacheck
        description: Lint and static analysis of Lua code
        entry: luacheck
        language: lua
        types: [lua]
